version: "3"

services:
  nginx:
    build: ./nginx
    image: alex88otus/nginx:0.1
    volumes:
      - ./cfg/etc/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./cfg/var/www/php:/var/www/php
    ports:
      - "8080:80"
    networks:
      - network001
    depends_on:
      - php
  php:
    build: ./php
    image: alex88otus/php:0.1
    volumes:
      - ./cfg/var/www/php:/var/www/php
      - ./cfg/etc/php7/php-fpm.conf:/etc/php7/php-fpm.conf
      - ./cfg/etc/php7/php-fpm.d:/etc/php7/php-fpm.d
    networks:
      - network001
networks:
  network001:
    driver: bridge
