#!/bin/bash

yum install -y wget gcc flex bison bc elfutils-libelf-devel openssl-devel perl
wget https://cdn.kernel.org/pub/linux/kernel/v5.x/linux-5.1.1.tar.xz
cp /boot/config-3.10.0-957.12.1.el7.x86_64 .
tar -xvf linux-5.1.1.tar.xz
cp config-3.10.0-957.12.1.el7.x86_64 linux-5.1.1/.config
cd linux-5.1.1/
make olddefconfig
make -j5
make -j5 modules_install install
cp .config ..
grub2-mkconfig -o /boot/grub2/grub.cfg
reboot

