# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"

  config.vm.define "master" do |master|
    master.vm.hostname = 'master'
    master.vm.network :private_network, ip: "192.168.5.100"
    master.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--cpus", 4]
      v.customize ["modifyvm", :id, "--memory", 1024]
    end
    master.vm.provision "shell", inline: <<-SHELL
    yum install -y https://repo.percona.com/yum/percona-release-latest.noarch.rpm
    percona-release setup ps80
    yum install -y nano percona-server-server
    cp /vagrant/conf/conf.d/* /etc/my.cnf.d/
    echo "!includedir /etc/my.cnf.d" >> /etc/my.cnf
    systemctl start mysql
    touch ~/.my.cnf
    echo "[client]" >> ~/.my.cnf
    echo "user=root" >> ~/.my.cnf
    echo "password=$(grep 'root@localhost:' /var/log/mysqld.log | awk '{print $13}')" >> ~/.my.cnf
    SHELL
  end

  config.vm.define "slave" do |slave|
    slave.vm.hostname = 'slave'
    slave.vm.network :private_network, ip: "192.168.5.150"
    slave.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--cpus", 4]
      v.customize ["modifyvm", :id, "--memory", 1024]
    end
    slave.vm.provision "shell", inline: <<-SHELL
    yum install -y https://repo.percona.com/yum/percona-release-latest.noarch.rpm
    percona-release setup ps80
    yum install -y nano percona-server-server
    cp /vagrant/conf/conf.d/* /etc/my.cnf.d/
    echo "!includedir /etc/my.cnf.d" >> /etc/my.cnf
    sed -i "s/server-id = 1/server-id = 2/" /etc/my.cnf.d/01-base.cnf
    sed -i "s/#replicate/replicate/g" /etc/my.cnf.d/05-binlog.cnf
    systemctl start mysql
    touch ~/.my.cnf
    echo "[client]" >> ~/.my.cnf
    echo "user=root" >> ~/.my.cnf
    echo "password=$(grep 'root@localhost:' /var/log/mysqld.log | awk '{print $13}')" >> ~/.my.cnf
    SHELL
  end
end
