# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
  :inetRouter => {
        :box_name => "centos/6",
        #:public => {:ip => '10.10.10.1', :adapter => 1},
        :net => [
                   {ip: '192.168.255.1', adapter: 2, netmask: "255.255.255.252", virtualbox__intnet: "router-net"},
                ]
  },

  :centralRouter => {
        :box_name => "centos/7",
        :net => [
                   {ip: '192.168.255.2', adapter: 2, netmask: "255.255.255.252", virtualbox__intnet: "router-net"},
                   {ip: '192.168.0.1', adapter: 3, netmask: "255.255.255.240", virtualbox__intnet: "routers"},
                   {ip: '192.168.0.17', adapter: 4, netmask: "255.255.255.240", virtualbox__intnet: "dir-net"},
                   {ip: '192.168.0.33', adapter: 5, netmask: "255.255.255.224", virtualbox__intnet: "hw-net"},
                   {ip: '192.168.0.65', adapter: 6, netmask: "255.255.255.192", virtualbox__intnet: "wifi-net"},
                ]
  },
  :inetRouter2 => {
    :box_name => "centos/7",
    :net => [
               {ip: '192.168.0.5', adapter: 2, netmask: "255.255.255.240", virtualbox__intnet: "routers"},
               {ip: '10.10.10.10', adapter: 3, netmask: "255.255.255.0", virtualbox__hostonly: "local"},
            ]
  },
  # :office1Router => {
  #       :box_name => "centos/7",
  #       :net => [
  #                  {ip: '192.168.0.3', adapter: 2, netmask: "255.255.255.240", virtualbox__intnet: "routers"},
  #                  {ip: '192.168.1.1', adapter: 3, netmask: "255.255.255.128", virtualbox__intnet: "dev1-net"},
  #                  {ip: '192.168.1.129', adapter: 4, netmask: "255.255.255.192", virtualbox__intnet: "testsrv1-net"},
  #                  {ip: '192.168.1.193', adapter: 5, netmask: "255.255.255.192", virtualbox__intnet: "hw1-net"},
  #               ]
  # },

  # :office2Router => {
  #       :box_name => "centos/7",
  #       :net => [
  #                  {ip: '192.168.0.4', adapter: 2, netmask: "255.255.255.240", virtualbox__intnet: "routers"},
  #                  {ip: '192.168.2.1', adapter: 3, netmask: "255.255.255.192", virtualbox__intnet: "dev2-net"},
  #                  {ip: '192.168.2.65', adapter: 4, netmask: "255.255.255.192", virtualbox__intnet: "testsrv2-net"},
  #                  {ip: '192.168.2.129', adapter: 5, netmask: "255.255.255.192", virtualbox__intnet: "mng-net"},
  #                  {ip: '192.168.2.193', adapter: 6, netmask: "255.255.255.192", virtualbox__intnet: "hw2-net"},
  #               ]
  # },

  :centralServer => {
    :box_name => "centos/7",
    :net => [
               {ip: '192.168.0.2', adapter: 2, netmask: "255.255.255.240", virtualbox__intnet: "routers"},
            ]
  },

  # :office1Server => {
  #   :box_name => "centos/7",
  #   :net => [
  #              {ip: '192.168.1.2', adapter: 2, netmask: "255.255.255.128", virtualbox__intnet: "dev1-net"},
  #           ]
  # },

  # :office2Server => {
  #   :box_name => "centos/7",
  #   :net => [
  #              {ip: '192.168.2.2', adapter: 2, netmask: "255.255.255.192", virtualbox__intnet: "dev2-net"},
  #           ]
  # },
}

Vagrant.configure("2") do |config|

  # config.vm.define "inetRouter2" do |v|
  #   v.vm.network :forwarded_port, host: 18080, guest: 8080
  #   v.vm.network "private_network", ip: "10.10.10.10"
  # end

  MACHINES.each do |boxname, boxconfig|

    config.vm.define boxname do |box|

        box.vm.box = boxconfig[:box_name]
        box.vm.host_name = boxname.to_s

        boxconfig[:net].each do |ipconf|
          box.vm.network "private_network", ipconf
        end
        
        if boxconfig.key?(:public)
          box.vm.network "public_network", boxconfig[:public]
        end

        box.vm.provision "shell", inline: <<-SHELL
          mkdir -p ~root/.ssh
                cp ~vagrant/.ssh/auth* ~root/.ssh
        SHELL
        
        case boxname.to_s
        when "inetRouter"
          box.vm.provision "shell", run: "always", inline: <<-SHELL
            echo "NOZEROCONF=yes" >> /etc/sysconfig/network
            echo "NETWORKING_IPV6=no" >> /etc/sysconfig/network
            echo "IPV6INIT=no" >> /etc/sysconfig/network
            service network restart
            iptables -t nat -A POSTROUTING ! -d 192.168.0.0/16 -o eth0 -j MASQUERADE
            ip route add 192.168.0.0/17 via 192.168.255.2 dev eth1
            sysctl -w net.ipv4.conf.all.forwarding=1
            sed -i '66s/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
            service sshd restart 
            echo "Otus2019" | sudo passwd --stdin vagrant
            iptables-restore < /vagrant/iptables.rules
            service iptables save
            SHELL
        when "centralRouter"
          box.vm.provision "shell", run: "always", inline: <<-SHELL
            echo "NOZEROCONF=yes" >> /etc/sysconfig/network
            echo "NETWORKING_IPV6=no" >> /etc/sysconfig/network
            echo "IPV6INIT=no" >> /etc/sysconfig/network
            echo "DEFROUTE=no" >> /etc/sysconfig/network-scripts/ifcfg-eth0 
            echo "GATEWAY=192.168.255.1" >> /etc/sysconfig/network-scripts/ifcfg-eth1
            systemctl restart network
            systemctl restart network
            ip route add 192.168.1.0/24 via 192.168.0.3 dev eth2
            ip route add 192.168.2.0/24 via 192.168.0.4 dev eth2
            sysctl -w net.ipv4.conf.all.forwarding=1
            yum install -y nmap
            SHELL
        when "inetRouter2"
          box.vm.provision "shell", run: "always", inline: <<-SHELL
            echo "NOZEROCONF=yes" >> /etc/sysconfig/network
            echo "NETWORKING_IPV6=no" >> /etc/sysconfig/network
            echo "IPV6INIT=no" >> /etc/sysconfig/network
            echo "DEFROUTE=no" >> /etc/sysconfig/network-scripts/ifcfg-eth0
            systemctl restart network
            systemctl restart network
            sysctl -w net.ipv4.conf.all.forwarding=1
            systemctl start firewalld.service
            iptables -I FORWARD -p tcp -d 192.168.0.2 --dport 80 -j ACCEPT
            iptables -t nat -A PREROUTING -p tcp --dport 8080 -j DNAT --to-destination 192.168.0.2:80
            SHELL
        # when "office1Router"
        #   box.vm.provision "shell", run: "always", inline: <<-SHELL
        #     echo "NOZEROCONF=yes" >> /etc/sysconfig/network
        #     echo "NETWORKING_IPV6=no" >> /etc/sysconfig/network
        #     echo "IPV6INIT=no" >> /etc/sysconfig/network
        #     echo "DEFROUTE=no" >> /etc/sysconfig/network-scripts/ifcfg-eth0 
        #     echo "GATEWAY=192.168.0.1" >> /etc/sysconfig/network-scripts/ifcfg-eth1
        #     systemctl restart network
        #     systemctl restart network
        #     sysctl -w net.ipv4.conf.all.forwarding=1
        #     SHELL
        # when "office2Router"
        #   box.vm.provision "shell", run: "always", inline: <<-SHELL
        #     echo "NOZEROCONF=yes" >> /etc/sysconfig/network
        #     echo "NETWORKING_IPV6=no" >> /etc/sysconfig/network
        #     echo "IPV6INIT=no" >> /etc/sysconfig/network
        #     echo "DEFROUTE=no" >> /etc/sysconfig/network-scripts/ifcfg-eth0 
        #     echo "GATEWAY=192.168.0.1" >> /etc/sysconfig/network-scripts/ifcfg-eth1
        #     systemctl restart network
        #     systemctl restart network
        #     sysctl -w net.ipv4.conf.all.forwarding=1
        #     SHELL
        when "centralServer"
          box.vm.provision "shell", run: "always", inline: <<-SHELL
            echo "NOZEROCONF=yes" >> /etc/sysconfig/network
            echo "NETWORKING_IPV6=no" >> /etc/sysconfig/network
            echo "IPV6INIT=no" >> /etc/sysconfig/network
            echo "DEFROUTE=no" >> /etc/sysconfig/network-scripts/ifcfg-eth0
            echo "GATEWAY=192.168.0.1" >> /etc/sysconfig/network-scripts/ifcfg-eth1
            systemctl restart network
            systemctl restart network
            yum install -y epel-release
            yum install -y nginx
            systemctl daemon-reload
            systemctl enable nginx
            systemctl start nginx
            ip route add 10.10.10.0/24 via 192.168.0.5 dev eth1
            SHELL
        # when "office1Server"
        #   box.vm.provision "shell", run: "always", inline: <<-SHELL
        #     echo "NOZEROCONF=yes" >> /etc/sysconfig/network
        #     echo "NETWORKING_IPV6=no" >> /etc/sysconfig/network
        #     echo "IPV6INIT=no" >> /etc/sysconfig/network
        #     echo "DEFROUTE=no" >> /etc/sysconfig/network-scripts/ifcfg-eth0
        #     echo "GATEWAY=192.168.1.1" >> /etc/sysconfig/network-scripts/ifcfg-eth1
        #     systemctl restart network
        #     systemctl restart network
        #     SHELL
        # when "office2Server"
        #   box.vm.provision "shell", run: "always", inline: <<-SHELL
        #     echo "NOZEROCONF=yes" >> /etc/sysconfig/network
        #     echo "NETWORKING_IPV6=no" >> /etc/sysconfig/network
        #     echo "IPV6INIT=no" >> /etc/sysconfig/network
        #     echo "DEFROUTE=no" >> /etc/sysconfig/network-scripts/ifcfg-eth0
        #     echo "GATEWAY=192.168.2.1" >> /etc/sysconfig/network-scripts/ifcfg-eth1
        #     systemctl restart network
        #     systemctl restart network
        #     SHELL
        end

      end

  end
  
  
end

