# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  config.vm.box = "centos/7"

  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  # config.vm.box_check_update = false

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # NOTE: This will enable public access to the opened port
  # config.vm.network "forwarded_port", guest: 80, host: 8080

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine and only allow access
  # via 127.0.0.1 to disable public access
  # config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  # config.vm.network "private_network", ip: "192.168.33.10"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  config.vm.provider "virtualbox" do |vb|
  #   # Display the VirtualBox GUI when booting the machine
  #   vb.gui = true
  #
  #   # Customize the amount of memory on the VM:
    vb.cpus = "12"
    vb.memory = "1024"
  end
  #
  # View the documentation for the provider you are using for more
  # information on available options.

  # Enable provisioning with a shell script. Additional provisioners such as
  # Ansible, Chef, Docker, Puppet and Salt are also available. Please see the
  # documentation for more information about their specific syntax and use.
  config.vm.provision "shell", inline: <<-SHELL
    cd /root/
    yum install -y redhat-lsb-core wget rpmdevtools rpm-build createrepo yum-utils gcc
    wget http://nginx.org/packages/centos/7/SRPMS/nginx-1.16.1-1.el7.ngx.src.rpm
    wget https://www.openssl.org/source/latest.tar.gz
    tar -xf latest.tar.gz
    rpm -i nginx-1.16.1-1.el7.ngx.src.rpm
    yum-builddep -y rpmbuild/SPECS/nginx.spec
    sed -i 's~with-debug~with-openssl=/root/openssl-1.1.1d~' rpmbuild/SPECS/nginx.spec
    rpmbuild -bb rpmbuild/SPECS/nginx.spec
    ll rpmbuild/RPMS/x86_64/
    yum localinstall -y rpmbuild/RPMS/x86_64/nginx-1.16.1-1.el7.ngx.x86_64.rpm
    systemctl start nginx
    systemctl status nginx
    mkdir /usr/share/nginx/html/repo
    cp rpmbuild/RPMS/x86_64/nginx-1.16.1-1.el7.ngx.x86_64.rpm /usr/share/nginx/html/repo
    wget https://www.percona.com/redir/downloads/percona-release/redhat/percona-release-1.0-15.noarch.rpm -O /usr/share/nginx/html/repo/percona-release-1.0-15.noarch.rpm
    createrepo /usr/share/nginx/html/repo/
    sed -i '/index  index.html/a autoindex on;' /etc/nginx/conf.d/default.conf
    nginx -t
    nginx -s reload
    sleep 10
    curl localhost/repo/
    echo "[otus]\nname=otus-linux\nbaseurl=http://localhost/repo\ngpgcheck=0\nenabled=1" >> /etc/yum.repos.d/otus.repo
    yum repolist enabled | grep otus
    yum list all | grep otus
    yum repoinfo otus
  SHELL
end
