# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.define "host" do |host|
    host.vm.box = "centos/7"
    host.vm.hostname = 'host'

    host.vm.network :private_network, ip: "192.168.11.11"
    host.vm.network :forwarded_port, guest: 22, host: 2200, id: "ssh"
    host.vm.network :forwarded_port, guest: 8888, host: 8888

    host.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--cpus", 4]
      v.customize ["modifyvm", :id, "--memory", 512]
      v.customize ["modifyvm", :id, "--name", "host"]
    end
    host.vm.provision "shell", inline: <<-SHELL
      yum install -y nano epel-release setools libsemanage-python policycoreutils-python
      yum install -y nginx
      SHELL
  end

end
