# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.define "server" do |server|
    server.vm.box = "centos/7"
    server.vm.hostname = 'server'

    server.vm.network :private_network, ip: "192.168.10.10"
    server.vm.network :forwarded_port, guest: 22, host: 2200, id: "ssh"


    server.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--cpus", 4]
      v.customize ["modifyvm", :id, "--memory", 2048]
      v.customize ["modifyvm", :id, "--name", "server"]
    end
    #server.vm.provision "shell", inline: <<-SHELL
    #SHELL
  end

  config.vm.define "client" do |client|
    client.vm.box = "centos/7"
    client.vm.hostname = 'client'

    client.vm.network :private_network, ip: "192.168.10.100"
    client.vm.network :forwarded_port, guest: 22, host: 2201, id: "ssh"

    client.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--cpus", 4]
      v.customize ["modifyvm", :id, "--memory", 512]
      v.customize ["modifyvm", :id, "--name", "client"]
    end
    #client.vm.provision "shell", inline: <<-SHELL
    #SHELL
  end

  config.vm.provision "ansible" do |ansible|
    ansible.verbose = "v"
    ansible.playbook = "nfs.yml"
  end

end
