---
- hosts: teamhosts
  tasks:
  - name: cp configs eth1 eth2 to teamhosts
    template:
      src: templates/ifcfg-eth
      dest: /etc/sysconfig/network-scripts/ifcfg-eth{{ item }}
      owner: root
      group: root
      mode: 0644
    with_items:
      - 1
      - 2
  - name: cp config team0 to teamhosts
    template:
      src: templates/ifcfg-team0_{{ inventory_hostname }}
      dest: /etc/sysconfig/network-scripts/ifcfg-team0
      owner: root
      group: root
      mode: 0644

- hosts: centralRouter
  tasks:
  - name: cp config eth3 to centralRouter
    template:
      src: templates/ifcfg-eth3
      dest: /etc/sysconfig/network-scripts/ifcfg-eth3
      owner: root
      group: root
      mode: 0644
- hosts: vlanhosts
  tasks:
  - name: cp config eth1 to vlanhosts
    template:
      src: templates/ifcfg-eth1
      dest: /etc/sysconfig/network-scripts/ifcfg-eth1
      owner: root
      group: root
      mode: 0644

- hosts: centralRouter
  tasks:
  - name: cp vlan configs to centralRouter
    template:
      src: templates/ifcfg-eth3.j2
      dest: /etc/sysconfig/network-scripts/ifcfg-eth3.{{ item }}
      owner: root
      group: root
      mode: 0644
    with_items:
      - 100
      - 101
- hosts: vlanhosts
  tasks:
  - name: cp vlan config to vlanhosts
    template:
      src: templates/ifcfg-eth1.j2
      dest: /etc/sysconfig/network-scripts/ifcfg-eth1.{{ vlanid }}
      owner: root
      group: root
      mode: 0644

- hosts: all
  tasks:
  - name: restart network
    systemd:
      name: network
      state: restarted

- hosts: inetRouter
  tasks:
  - name: Enable IPv4 forwarding
    sysctl:
      name: net.ipv4.conf.all.forwarding
      value: 1
      sysctl_set: yes
